name: Shubhangi CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate HTML file exists
        run: |
          if [ -f index.html ]; then
            echo "index.html found!"
          else
            echo "index.html missing!"
            exit 1
          fi

      - name: Show file contents
        run: cat index.html

      - name: Pipeline success
        run: echo "Shubhangi's static page pipeline passed!"
