name: Shubhangi CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t shubhangi-app:latest .

      - name: Test image runs
        run: |
          docker run -d -p 8080:80 shubhangi-app:latest
          sleep 3
          curl http://localhost:8080 | grep "Shubhangi"
          echo "Docker image working!"
